SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS 'TOTAL_SALES'
FROM BOOK B
    JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES S
        ON B.BOOK_ID = S.BOOK_ID
WHERE MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;