SELECT E1.ID
        # E2.ID AS 'PARENT_1',
        # E3.ID AS 'PARENT_2',
        
FROM ECOLI_DATA E1
    LEFT JOIN ECOLI_DATA E2
    ON E1.PARENT_ID = E2.ID
    LEFT JOIN ECOLI_DATA E3
    ON E2.PARENT_ID = E3.ID
    
WHERE (E2.PARENT_ID IS NOT NULL)
    AND (E3.PARENT_ID IS NULL)
    
ORDER BY E1.ID ASC;