WITH PR AS(
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS 'P_RANK'
    FROM ECOLI_DATA
)

SELECT ID,
    CASE WHEN P_RANK <= 0.25 THEN 'CRITICAL'
        WHEN P_RANK <= 0.5 THEN 'HIGH'
        WHEN P_RANK <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
        END AS 'COLONY_NAME'
FROM PR
ORDER BY ID ASC;