SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_INS INS
    RIGHT JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE (INS.SEX_UPON_INTAKE LIKE "Intact%")
    AND (OUTS.SEX_UPON_OUTCOME NOT LIKE "Intact%")
ORDER BY OUTS.ANIMAL_ID;