WITH CHECK_RENTAL AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT(END_DATE, '%Y-%m-%d')
)

SELECT DISTINCT C.CAR_ID, CASE WHEN CR.CAR_ID IS NOT NULL THEN '대여중' ELSE '대여 가능' END AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    LEFT JOIN CHECK_RENTAL CR
    ON C.CAR_ID = CR.CAR_ID
ORDER BY C.CAR_ID DESC;
    