SELECT PD.PRODUCT_ID, PD.PRODUCT_NAME, PD.PRICE * SUM(OD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PD
    JOIN FOOD_ORDER OD
    ON PD.PRODUCT_ID = OD.PRODUCT_ID
WHERE YEAR(OD.PRODUCE_DATE) = 2022 AND MONTH(OD.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
