WITH SUBQ AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (MONTH(START_DATE) BETWEEN 8 AND 10)
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
)

SELECT MONTH(START_DATE) AS 'MONTH', C.CAR_ID, COUNT(C.CAR_ID) AS 'RECORDS'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    JOIN SUBQ S
    ON C.CAR_ID = S.CAR_ID
WHERE (S.CAR_ID IS NOT NULL) AND (MONTH(START_DATE) BETWEEN 8 AND 10)
GROUP BY MONTH(START_DATE), C.CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, C.CAR_ID DESC;
