SELECT YEAR, B.max_size - A.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS A
    JOIN
        (
        SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS max_size
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
        ) AS B
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
    
ORDER BY YEAR, YEAR_DEV