WITH MAX_VIEW AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD 
    ORDER BY VIEWS DESC
    LIMIT 1
    )
    
SELECT CONCAT('/home/grep/src/', FI.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE FI
    JOIN MAX_VIEW MV
    ON FI.BOARD_ID = MV.BOARD_ID
ORDER BY FILE_ID DESC;