WITH ROUND_FISH AS (
    SELECT ID, FISH_TYPE,
        CASE WHEN LENGTH <= 10 THEN 10
             WHEN LENGTH IS NULL THEN 10
             ELSE LENGTH
        END AS 'LENGTH'
    FROM FISH_INFO
), 

TEMP AS (
    SELECT FISH_TYPE
    FROM ROUND_FISH
    GROUP BY FISH_TYPE
    HAVING AVG(LENGTH) >= 33
) 
    
SELECT COUNT(*) AS 'FISH_COUNT', MAX(LENGTH) AS 'MAX_LENGTH', I.FISH_TYPE
FROM ROUND_FISH I
    RIGHT JOIN TEMP T
    ON I.FISH_TYPE = T.FISH_TYPE
GROUP BY I.FISH_TYPE
ORDER BY FISH_TYPE ASC;